### ISSUE TITLE
current time

### ISSUE THREAD

**Issue by princevani** [Muhammad-1990/iqoption#1]
I want to get the current os time however i am unable to do so, i tried different methods and programming concepts but i am unable to get it, can you please help me this.

**Comment by Muhammad-1990** [comment]
hi,

yea this is tricky, 
why do you want the time?

instrument {
    name = 'New Indicator',
    icon = 'indicators:MA',
    overlay = true
}

-- get any currency
local ticker_id = get_ticker_id("EURUSD")

-- get currency candles
local m =  security (ticker_id, "1m")

-- check for valid time
if (get_value(m.open_time) ~= nil) then
   
 -- get timestamp
    timestamp = get_value(m.open_time)
    
-- convert timestamp to a date table
    theTime = date(timestamp)
  
-- print minute
    print(theTime.min)
end

**Comment by Muhammad-1990** [comment]
theres some kind of bug thats crashing if you not on the 1minute timeframe... be careful of switching timeframes....

need more time to figure this out, but does it help? where are you getting stuck?

**Comment by princevani** [comment]
hey, thank you for the help, actually i am able to get the minute of current_candle but actually i am finding a way to get the remaining time to purchase, i mean I want to count the seconds for each candles when it open. Futher then i have my script that is working 93% accuracy for prediction, the only issue is the time of the signals appear. Thats why i want to calcuate the seconds remaining for the current candle so that i can control my signals in such a way that if the condition meets in the first 20 seconds of the candle it will plot the signal else it will not. This will help me filtering the false signals that apperar after 20 sec of cuurent candle.

**Comment by Muhammad-1990** [comment]
Ok will need a bit more time to give it some thought…

will it work if you check for a new 1min candle and then just count 2 10second candles?

**Comment by princevani** [comment]
yes definetly it will help, i have tried this but i failed to code it accurately, 1min timeframe candle can have 6*10 sec candles so if we can track the first 2 candle and if the condition of my script meets before the closing of 2nd 10th seconds candle then we can plot the signal, else we have to skip the next 4 remaining candles of 10sec and reapeat it for the next candles. 

Also the above code you have given is soo long whereas we can get the same output with -- date(open_time[0]).min  this code only. 
if we replace "min" to "sec" this is giving me "0" that means the seconds are not updating in the above date function or this may be a bug in the original source code, but we can change it "hour", week year anything and it is perfectly working.

**Comment by Muhammad-1990** [comment]
looks like you have to be on the 10s timeframe... also if i switch timeframes then it crashes, not sure if the same will happen to you.

it works now, main difference is using the close time, which makes sense.


instrument {
    name = 'New Indicator',
    icon = 'indicators:MA',
    overlay = true
}

-- signal trigger
local readyForSignal = false

-- get 10s data
sec = security (current_ticker_id, "10s")
-- check if data valid
if sec.close_time[0] ~= nil then
    timestamp = sec.close_time[0]
    theTime = date(timestamp)
    -- check for first 20s
    if theTime.sec > 0 and theTime.sec <= 20 then
        -- publish signal
        readyForSignal = true
    else
        -- retract signal
       readyForSignal = false
    end
end

-- get 1min data
min = security (current_ticker_id, "1m")

-- my strategy
if min.close[0] > min.close[1] then
   -- should we give signal?
   if readyForSignal == true then
        print("buy")
        plot_shape(true
            ,"Buy"
            ,shape_style.triangleup
            ,shape_size.tiny
            ,"green"
            ,shape_location.belowbar
            ,0
            ,""
            ,"green" 
)
   end    
end

**Comment by Muhammad-1990** [comment]
can you share your script with me?

**Comment by Muhammad-1990** [comment]
![image](https://user-images.githubusercontent.com/53302444/148525043-a7ca62df-fa2c-48ea-a0c7-e61767944fd2.png)

**Comment by princevani** [comment]
i run the code and when i switch tab it hangs and not opening my application again, it crash always, and i uninstall the application and reinstall and i saw saw that ther is no scripts, i lost all my hard waork of the months..  i dont know how to recover files

**Comment by Muhammad-1990** [comment]
Sorry to hear that…. Check this location for the scripts

app-local/roaming/iqoption 

When it crashed on my pc I just closed and reopened and it worked.

there was also a Jain file that it uses to start up and you can remove the script in that json.
That way when the app starts it doesn’t load the faulty script…

hope you find your scripts

**Comment by Muhammad-1990** [comment]
You don’t end up finding it I can help you re code it

**Comment by princevani** [comment]
its ok, its not your mistake, actually i retried to code half of my script but, its not same as before also i forgot some of perameters that i have set, once coompleted i will share it., i have tried different recovery software but they come to be paid subscription in the end.
