### ISSUE TITLE
counter

### ISSUE THREAD

**Issue by Jnonym** [Muhammad-1990/iqoption#2]
hello bro,,
its possible to count prev history value, such how many buy or sell condition has occured or by just ploted at certain period,, and the result can be plot on the charrt,,, its for backtesting some strategy or indicator,,, just to make easier so dont have to scroll back the chart

**Comment by Muhammad-1990** [comment]
Hey man,

not sure I understand you but I don’t think it can be done.

you have to scroll back to load the historic rates into the chat.
I will have to check if there is a method to load the history. Like a getRates() method. 

Not near the charts right now, so will get back to you soon…

**Comment by Muhammad-1990** [comment]
This feature is currently not supported by Iq option platform.
